name: sample_flutter_web_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.8
  json_annotation: 3.1.1
  http: ^0.12.0+2
  url_launcher: ^5.7.10
  modal_progress_hud: ^0.1.3




  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc: ^6.1.3
  flutter_bloc: ^6.1.3
  provider: ^4.3.3
  build_runner: ^1.0.0
  json_serializable: 3.5.1


flutter:


  uses-material-design: true

  assets:
    - images/spring.png
    - images/download.png

  fonts:
    - family: IranSans
      fonts:
        - asset: fonts/iran_sans_normal.ttf

    - family: IranSansFanum
      fonts:
        - asset: fonts/iran_sans_fanum_normal.ttf


